### PR TITLE
Arbitrary length cite lists properly parsed

### PR DESCRIPTION
**Pull request by mdelcambre**
This is an attempt to address issue #2

This looks for citation lists of arbitrary length then passes them to a function with a simpler regex to add cite elements to every citation matched.

Test Code:

```python
def code_citer(match_object):
    in_str = match_object.group(0)
    out_str = re.sub(r'(\d+-\d+(?::\d)?\w*(?:\.\d+\w*)?)', '<cite abs="\\1">\\1</cite>', in_str)
    return out_str

subs = (re.compile(r'(§\s+(?:\d+-\d+(?::\d)?\w*(?:\.\d+\w*)?(?:\(\w+\))*[\s,]+)*(?:and)?\s?)(\d+-\d+(?::\d)?\w*(?:\.\d+\w*)?)'), code_citer)
node_text = subs[0].sub(subs[1], case)
print(case)
print(node_text)
```

Test Input:

    (3) Alternates to the officials referred to in paragraphs (1) and (2) of this section, where permitted by political party rules; and
    (7) The term "felony" includes any crime committed in the District of Columbia referred to in §§ 1-1001.14, 1-1162.32, and 1-1163.35.
    (8) The term "Council" or "Council of the District of Columbia" means the Council of the District of Columbia established pursuant to the District of Columbia Home Rule Act [§ 1-201.01 et seq.]. principle, or any question submitted to vote at a public election by means of an initiative, referendum or recall as authorized in amendments numbered 1 and 2 to Title IV of the Home Rule Act (§§ 1-204.101 to 1-204.115). Such entities shall be treated as a political committee as defined in § 1-1161.01(44) for purposes of this subchapter.
    (17) The term "voter registration agency" means an office designated under § 1-1001.07(d)(1) and the National Voter Registration Act of 1993 to perform voter registration activities.
    (23) The term "Help America Vote Act of 2002" means the Help America Vote Act of 2002, approved October 29, 2002 (116 Stat. 1666; 42 U.S.C. § 15301 et seq.).

Test Output:

    (3) Alternates to the officials referred to in paragraphs (1) and (2) of this section, where permitted by political party rules; and
    (7) The term "felony" includes any crime committed in the District of Columbia referred to in §§ <cite abs="1-1001.14">1-1001.14</cite>, <cite abs="1-1162.32">1-1162.32</cite>, and <cite abs="1-1163.35">1-1163.35</cite>.
    (8) The term "Council" or "Council of the District of Columbia" means the Council of the District of Columbia established pursuant to the District of Columbia Home Rule Act [§ <cite abs="1-201.01">1-201.01</cite> et seq.]. principle, or any question submitted to vote at a public election by means of an initiative, referendum or recall as authorized in amendments numbered 1 and 2 to Title IV of the Home Rule Act (§§ <cite abs="1-204.101">1-204.101</cite> to 1-204.115). Such entities shall be treated as a political committee as defined in § <cite abs="1-1161.01">1-1161.01</cite>(44) for purposes of this subchapter.
    (17) The term "voter registration agency" means an office designated under § <cite abs="1-1001.07">1-1001.07</cite>(d)(1) and the National Voter Registration Act of 1993 to perform voter registration activities.
    (23) The term "Help America Vote Act of 2002" means the Help America Vote Act of 2002, approved October 29, 2002 (116 Stat. 1666; 42 U.S.C. § 15301 et seq.).

### CODE REVIEW

**Comment by mdelcambre** [comment]
I hadn't realized that the xml code was in the repo and I could do a full test. Looking into a unicode error it appears right now.

**Comment by dgreisen-cfpb** [comment]
Thanks! I'll pull it down and take a look.

**Comment by dgreisen-cfpb** [comment]
Could you add a comment to https://github.com/DCCouncil/dc-law/issues/1 stating that you license contributions to these repos under CC0?

**Comment by dgreisen-cfpb** [comment]
It is much better than it was. Thank you. It looks like you are keying multiple sites off of a single § symbol, is that correct? If so, I think the stricter method would be to only look for multiple sites after §§. It also doesn't handle "through", which I think should be relatively easy to add in: `as authorized by §§ <cite abs="34-2405.01">34-2405.01</cite> through 34-2405.08;` should have a cite tag around the second section definition.

**Comment by mdelcambre** [comment]
Yeah we could add back the simple one off of a single §. Then make the list
go only for §§.
'through' should be easy to add.

**Comment by mdelcambre** [comment]
The only thing I will note is that I changed the single citation to have the § outside of the cite element to match the list citations.

**Comment by dgreisen-cfpb** [comment]
Almost there. Here's the serious stress test - if we can get this to pass, I think, it will be able to handle anything:

Enactment upon adoption of federal legislation: Section 4 of D.C. Law 11-254 provided that “§§ 47-101, 47-117, 47-130, 47-301, 47-302, 47-303, 47-304, 47-304.1, 47-305, 47-310, 47-312, 47-317.1 through 47-317.6, 47-321 through 47-325, 47-327 through 47-331, and 47-332 through 47-334 of Title 47 [§§ 1-204.41, 1-204.55, 1-204.50, 1-204.42, 1-204.43, 1-204.44, 1-204.46, 1-204.53, 1-204.47, 1-204.48, 1-204.49, 1-204.24a through 1-204.24e, 47-317.06, 1-204.61 through 1-204.65, 1-204.71 through 1-204.75, 1-204.81, 1-204.85, 1-204.86 and 1-204.90, 2001 Ed.] of the District of Columbia Code shall be enacted as part of Title 47 upon the adoption by Congress of legislation so enacting these sections.”

right now, it returns:

Enactment upon adoption of federal legislation: Section 4 of <cite doc="D.C. Law 11-254">D.C. Law 11-254</cite> provided that “§<cite abs="47-101">§ 47-101</cite>, 47-117, 47-130, 47-301, 47-302, 47-303, 47-304, 47-304.1, 47-305, 47-310, 47-312, 47-317.1 through 47-317.6, 47-321 through 47-325, 47-327 through 47-331, and 47-332 through 47-334 of Title 47 [§<cite abs="1-204.41">§ 1-204.41</cite>, 1-204.55, 1-204.50, 1-204.42, 1-204.43, 1-204.44, 1-204.46, 1-204.53, 1-204.47, 1-204.48, 1-204.49, 1-204.24a through 1-204.24e, 47-317.06, 1-204.61 through 1-204.65, 1-204.71 through 1-204.75, 1-204.81, 1-204.85, 1-204.86 and 1-204.90, 2001 Ed.] of the District of Columbia Code shall be enacted as part of Title 47 upon the adoption by Congress of legislation so enacting these sections.”

Happy to work with you on it this evening.

**Comment by dgreisen-cfpb** [comment]
If we can't make that one work this evening, that's fine. I think what you've got so far gets us 95% of the way there, which is a whole lot further than what I had.

**Comment by mdelcambre** [comment]
```xml
<text>Enactment upon adoption of federal legislation: Section 4 of <cite
doc="D.C. Law 11-254">D.C. Law 11-254</cite> provided that “§§ <cite
abs="47-101">47-101</cite>, <cite abs="47-117">47-117</cite>, <cite
abs="47-130">47-130</cite>, <cite abs="47-301">47-301</cite>, <cite
abs="47-302">47-302</cite>, <cite abs="47-303">47-303</cite>, <cite
abs="47-304">47-304</cite>, <cite abs="47-304.1">47-304.1</cite>, <cite
abs="47-305">47-305</cite>, <cite abs="47-310">47-310</cite>, <cite
abs="47-312">47-312</cite>, <cite abs="47-317.1">47-317.1</cite> through
<cite abs="47-317.6">47-317.6</cite>, <cite abs="47-321">47-321</cite>
through <cite abs="47-325">47-325</cite>, <cite abs="47-327">47-327</cite>
through <cite abs="47-331">47-331</cite>, and <cite
abs="47-332">47-332</cite> through 47-334 of Title 47 §§ <cite
abs="1-204.41">1-204.41</cite>, <cite abs="1-204.55">1-204.55</cite>, <cite
abs="1-204.50">1-204.50</cite>, <cite abs="1-204.42">1-204.42</cite>, <cite
abs="1-204.43">1-204.43</cite>, <cite abs="1-204.44">1-204.44</cite>, <cite
abs="1-204.46">1-204.46</cite>, <cite abs="1-204.53">1-204.53</cite>, <cite
abs="1-204.47">1-204.47</cite>, <cite abs="1-204.48">1-204.48</cite>, <cite
abs="1-204.49">1-204.49</cite>, <cite abs="1-204.24a">1-204.24a</cite>
through <cite abs="1-204.24e">1-204.24e</cite>, <cite
abs="47-317.06">47-317.06</cite>, <cite abs="1-204.61">1-204.61</cite>
through <cite abs="1-204.65">1-204.65</cite>, <cite
abs="1-204.71">1-204.71</cite> through <cite
abs="1-204.75">1-204.75</cite>, <cite abs="1-204.81">1-204.81</cite>, <cite
abs="1-204.85">1-204.85</cite>, <cite abs="1-204.86">1-204.86</cite> and
<cite abs="1-204.90">1-204.90</cite>, 2001 Ed. of the District of Columbia
Code shall be enacted as part of Title 47 upon the adoption by Congress of
legislation so enacting these sections.”</text>
```

**Comment by mdelcambre** [comment]
Here is the most recent output

```xml
<text>Enactment upon adoption of federal legislation: Section 4 of <cite
doc="D.C. Law 11-254">D.C. Law 11-254</cite> provided that “§§ <cite
abs="47-101">47-101</cite>, <cite abs="47-117">47-117</cite>, <cite
abs="47-130">47-130</cite>, <cite abs="47-301">47-301</cite>, <cite
abs="47-302">47-302</cite>, <cite abs="47-303">47-303</cite>, <cite
abs="47-304">47-304</cite>, <cite abs="47-304.1">47-304.1</cite>, <cite
abs="47-305">47-305</cite>, <cite abs="47-310">47-310</cite>, <cite
abs="47-312">47-312</cite>, <cite abs="47-317.1">47-317.1</cite> through
<cite abs="47-317.6">47-317.6</cite>, <cite abs="47-321">47-321</cite>
through <cite abs="47-325">47-325</cite>, <cite abs="47-327">47-327</cite>
through <cite abs="47-331">47-331</cite>, and <cite
abs="47-332">47-332</cite> through 47-334 of Title 47 §§ <cite
abs="1-204.41">1-204.41</cite>, <cite abs="1-204.55">1-204.55</cite>, <cite
abs="1-204.50">1-204.50</cite>, <cite abs="1-204.42">1-204.42</cite>, <cite
abs="1-204.43">1-204.43</cite>, <cite abs="1-204.44">1-204.44</cite>, <cite
abs="1-204.46">1-204.46</cite>, <cite abs="1-204.53">1-204.53</cite>, <cite
abs="1-204.47">1-204.47</cite>, <cite abs="1-204.48">1-204.48</cite>, <cite
abs="1-204.49">1-204.49</cite>, <cite abs="1-204.24a">1-204.24a</cite>
through <cite abs="1-204.24e">1-204.24e</cite>, <cite
abs="47-317.06">47-317.06</cite>, <cite abs="1-204.61">1-204.61</cite>
through <cite abs="1-204.65">1-204.65</cite>, <cite
abs="1-204.71">1-204.71</cite> through <cite
abs="1-204.75">1-204.75</cite>, <cite abs="1-204.81">1-204.81</cite>, <cite
abs="1-204.85">1-204.85</cite>, <cite abs="1-204.86">1-204.86</cite> and
<cite abs="1-204.90">1-204.90</cite>, 2001 Ed. of the District of Columbia
Code shall be enacted as part of Title 47 upon the adoption by Congress of
legislation so enacting these sections.”</text>
```

**Comment by mdelcambre** [comment]
I rebased to collapse into a single commit

**Pull request merged**
